### PR TITLE
Work on testing pipeline

### LINKED ISSUE #1: Add a GitHub Actions-based testing workflow
Add a testing workflow using GitHub Actions.

As part of the testing workflow, check that the provenance output conforms to our [pipeline-provenance-schema](https://github.com/BCCDC-PHL/pipeline-provenance-schema)

### LINKED ISSUE #6: Remove `--versioned_outdir` param
The `--versioned_outdir` param was intended to handle use-cases that we just don't run into much. It wasn't being used consistently in this pipeline either, so it should be removed.

### PR DESCRIPTION
**Pull request by dfornika**
Fixes #1 
Fixes #6 

As part of the GitHub Actions-based testing workflow involves checking the provenance outputs against our [pipeline-provenance-schema](https://github.com/BCCDC-PHL/pipeline-provenance-schema) this PR also includes updates to the provenance file format.

Superficial modifications have been made to the pipeline's conda envs. Their contents should remain the same, but their names and hashes have been updated. This will cause new conda envs to be created when this version of the pipeline is run for the first time.

### CODE REVIEW

**Comment by dfornika** [comment]
I think I've pushed this along as far as I can in this PR. The test pipeline is passing, but fluviewer appears to be failing in the test environment. I'm having trouble collecting an error message in the artifacts generated by the testing pipeline.

If possible I'd like to merge this as-is and follow up with smaller PR(s) to fix the remaining issue.

**Comment by JamesZlosnik** [comment]
Thank you Dan!!

@jpalmer37 would you mind running this on a test run?  I'll do the same and report back here.

James

**Comment by JamesZlosnik** [comment]
tested on a test dataset and worked great - we can merge this now.

**Review by JamesZlosnik — APPROVED** [review]
tested on a test data set, worked well.

**Comment by jpalmer37** [comment]
My apologies, didn't catch you in time. I was caught up debugging a very odd state that I've run into before where all outputs are accounted for but for some reason all the provenance processes fail to register and run. 

Aside from that, the pipeline seems to be working fine on my side!

**Pull request merged**
